name = "AtlasMap"
license = "Apache-2.0"
licenselink = "https://github.com/atlasmap/atlasmap/blob/master/LICENSE.md"
description = "Data mapping as a service"
homepage = "https://www.atlasmap.io/"
tags = []
features = []
min_version = "0.20.6"

[author]
  name = "AtlasMap Developers"
  homepage = "https://www.atlasmap.io/"

[[docs.sidenav]]
    name = "code"
    weight = -110
    identifier = "code"
    url = "https://github.com/atlasmap"

